FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm config set registry https://registry.npmjs.org/ && \
    npm cache clean --force && \
    npm install --legacy-peer-deps --no-audit --no-fund

COPY . .

EXPOSE 3004
CMD ["npm", "run", "dev"]
