FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm cache clean --force && \
    npm install --legacy-peer-deps --registry=https://registry.npmjs.org/

COPY . .

EXPOSE 3004
CMD ["npm", "run", "dev"]
